language: erlang
otp_release:
  - 17.0
branches:
  only:
    - master
before_install:
  - sudo apt-get update
  - sudo apt-get install clang
  - export CC=clang
  - git clone git://github.com/elixir-lang/elixir --depth=1 --branch=v0.13.2
  - make -C elixir
  - git submodule update --init --recursive
before_script:
  - "export PATH=`pwd`/elixir/bin:$PATH"
script: "make test"
