sudo: false

language: elixir

otp_release:
  - 17.4
  - 17.3
  - 17.1
  - 17.0

elixir: 1.0.4

env:
  matrix:
    - CC=clang
    - CC=gcc

after_script:
  - MIX_ENV=docs mix inch.report

after_success:
  - mix compile
  - mix coveralls.travis
