language: erlang
otp_release:
  - R16B02
  - R16B01
  - R16B
branches:
  only:
    - master
before_install:
  - git clone https://github.com/elixir-lang/elixir
  - cd elixir && make && cd ..
  - cd .. && mv discount.ex discount && cd discount
  - git submodule update --init --recursive
before_script:
  - "export PATH=`pwd`/elixir/bin:$PATH"
script: "MIX_ENV=test mix test"
